# server details
server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level: debug

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/euphoria
      username: root
      password: mysql@1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

